# Generated by Django 3.2.25 on 2024-11-20 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('file', models.FileField(upload_to='drawings/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LandDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_area_in_sq_ft', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=255)),
                ('building_in_sq_ft', models.FloatField()),
                ('survey_number', models.CharField(blank=True, max_length=100, null=True)),
                ('building_type', models.CharField(choices=[('G+0', 'G+0'), ('G+1', 'G+1'), ('G+2', 'G+2'), ('G+3', 'G+3'), ('G+4', 'G+4'), ('G+5', 'G+5'), ('G+6', 'G+6'), ('G+7', 'G+7'), ('G+8', 'G+8'), ('Tower', 'Tower')], max_length=50)),
                ('is_approved', models.BooleanField(default=False)),
                ('attachemnts', models.FileField(blank=True, null=True, upload_to='land_attachments/')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='messages/files/')),
                ('read_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=100)),
                ('documents', models.ManyToManyField(blank=True, to='core.Document')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=200)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('current_phase', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='core.projects')),
            ],
        ),
        migrations.DeleteModel(
            name='PhoneOTP',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='land_details',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='property_type',
        ),
        migrations.RemoveField(
            model_name='maintainanceprofile',
            name='jobs_completed',
        ),
        migrations.AddField(
            model_name='maintainanceprofile',
            name='projects_completed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='constructionprofile',
            name='company_profile',
            field=models.FileField(blank=True, upload_to='company_profiles/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='constructionprofile',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='constructionprofile',
            name='portfolio',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='constructionprofile',
            name='projects_completed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultantprofile',
            name='company_profile',
            field=models.FileField(blank=True, upload_to='company_profiles/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='consultantprofile',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultantprofile',
            name='portfolio',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultantprofile',
            name='projects_completed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interiorprofile',
            name='company_profile',
            field=models.FileField(blank=True, upload_to='company_profiles/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='interiorprofile',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interiorprofile',
            name='portfolio',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interiorprofile',
            name='projects_completed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintainanceprofile',
            name='company_profile',
            field=models.FileField(blank=True, upload_to='company_profiles/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='maintainanceprofile',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintainanceprofile',
            name='portfolio',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smarthomeprofile',
            name='company_profile',
            field=models.FileField(blank=True, upload_to='company_profiles/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='smarthomeprofile',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smarthomeprofile',
            name='portfolio',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smarthomeprofile',
            name='projects_completed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Consultant', 'Consultant'), ('Interior Designer', 'Interior Designer'), ('Construction', 'Construction'), ('Maintainance', 'Maintainance'), ('Smart_Home', 'Smart_Home'), ('Admin', 'Admin')], max_length=50),
        ),
        migrations.AddField(
            model_name='quotation',
            name='service_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projects',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.customerprofile'),
        ),
        migrations.AddField(
            model_name='projects',
            name='service_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='phase',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='core.projects'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='landdetail',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_details', to='core.customerprofile'),
        ),
        migrations.AddField(
            model_name='drawing',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.consultantprofile'),
        ),
        migrations.AddField(
            model_name='drawing',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawings', to='core.projects'),
        ),
        migrations.AddField(
            model_name='document',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.projects'),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
