# Generated by Django 3.2.25 on 2024-11-21 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20241120_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='details',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='stage',
            field=models.CharField(default='General', max_length=50),
        ),
        migrations.AddField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='quotation',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quotation',
            name='service_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_providers', to=settings.AUTH_USER_MODEL),
        ),
    ]
