# Generated by Django 3.2.25 on 2025-05-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20250526_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phase',
            name='customer_attachement',
        ),
        migrations.AddField(
            model_name='phase',
            name='customer_attachements',
            field=models.ManyToManyField(blank=True, related_name='attached_to_phases', to='core.Document'),
        ),
    ]
