# Generated by Django 3.2.25 on 2025-05-31 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20250526_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='display_priority',
            field=models.IntegerField(default=100, help_text='Lower numbers show higher in listings (ex: 10=VIP, 20=Premium, 100=Free)'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_approved_provider',
            field=models.BooleanField(default=False, help_text='True if this service provider application has been reviewed by ardy admin.'),
        ),
        migrations.CreateModel(
            name='PhaseUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='core.phase')),
                ('update_attachments', models.ManyToManyField(blank=True, related_name='attached_to_updates', to='core.Document')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PaymentClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_claimed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(help_text='Description of work completed for this claim')),
                ('status', models.CharField(choices=[('PendingReview', 'Pending Review'), ('ApprovedByCustomer', 'Approved By Customer'), ('ApprovedByArdy', 'Approved By Ardy'), ('Paid', 'Paid'), ('Rejected', 'Rejected')], default='PendingReview', max_length=50)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by_customer_at', models.DateTimeField(blank=True, null=True)),
                ('processed_by_ardy_at', models.DateTimeField(blank=True, null=True)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_claims', to='core.phase')),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('supporting_documents', models.ManyToManyField(blank=True, to='core.Document')),
                ('transaction_ref', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.transaction')),
            ],
        ),
    ]
