# Generated by Django 3.2.25 on 2024-11-21 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20241121_1012'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
