# Generated by Django 3.2.25 on 2025-05-17 06:50

from django.db import migrations


def create_free_subscription_plan(apps, schema_editor):
    SubscriptionPlan = apps.get_model('core', 'SubscriptionPlan')

    if not SubscriptionPlan.objects.filter(name="Free").exists():
        SubscriptionPlan.objects.create(
        name="Free",
        user_type="Customer",
        price=0.00,
        features={},
        is_active=True
    )

def delete_free_subscription_plan(apps, schema_editor):
    SubscriptionPlan = apps.get_model('core','SubscriptionPlan')
    SubscriptionPlan.objects.filter(name='Free').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_companyprofile_engagementlog_featuredlisting_lead_milestone_phoneotp_referral_review_subpromocode_tr')
    ]

    operations = [
        migrations.RunPython(create_free_subscription_plan, reverse_code=delete_free_subscription_plan),
    ]


