# Generated by Django 3.2.25 on 2025-05-17 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_create_free_subscription_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landdetail',
            name='building_in_sq_ft',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.subscriptionplan'),
        ),
    ]
