# Generated by Django 3.2.25 on 2025-05-17 07:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20250517_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+9999999999'. Up to 14 digits allowed.", regex='^\\+?1?\\d{9,14}$')])),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.CharField(blank=True, max_length=9, null=True)),
                ('count', models.IntegerField(default=0, help_text='Number of OTP sent')),
                ('otp_type', models.CharField(choices=[('signup', 'Signup'), ('reset_password', 'Reset Password')], default='signup', max_length=20)),
                ('social_login_token', models.CharField(blank=True, default=None, max_length=1000, null=True)),
            ],
            options={
                'unique_together': {('phone', 'email')},
            },
        ),
        migrations.DeleteModel(
            name='PhoneOTP',
        ),
    ]
