# Generated by Django 3.2.25 on 2025-05-17 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20250517_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='employees',
        ),
        migrations.AddField(
            model_name='userotp',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL),
        ),
    ]
