# Generated by Django 3.2.25 on 2025-05-17 07:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_employeerelationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='company_employees', through='core.EmployeeRelationship', to=settings.AUTH_USER_MODEL),
        ),
    ]
