# Generated by Django 3.2.25 on 2025-05-17 08:23

import core.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20250517_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='signup_type',
        ),
        migrations.AlterField(
            model_name='constructionprofile',
            name='company_profile',
            field=models.FileField(blank=True, upload_to=core.models.user.company_profile_upload_path),
        ),
        migrations.AlterField(
            model_name='consultantprofile',
            name='company_profile',
            field=models.FileField(blank=True, upload_to=core.models.user.company_profile_upload_path),
        ),
        migrations.AlterField(
            model_name='interiorprofile',
            name='company_profile',
            field=models.FileField(blank=True, upload_to=core.models.user.company_profile_upload_path),
        ),
        migrations.AlterField(
            model_name='maintainanceprofile',
            name='company_profile',
            field=models.FileField(blank=True, upload_to=core.models.user.company_profile_upload_path),
        ),
        migrations.AlterField(
            model_name='smarthomeprofile',
            name='company_profile',
            field=models.FileField(blank=True, upload_to=core.models.user.company_profile_upload_path),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='features',
            field=models.JSONField(default=dict, help_text='JSON structure for features'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='user_type',
            field=models.CharField(choices=[('1', 'Customer'), ('2', 'Service Provider')], max_length=50),
        ),
        migrations.AddConstraint(
            model_name='usersubscription',
            constraint=models.UniqueConstraint(fields=('user', 'plan'), name='unique_user_subscription'),
        ),
    ]
