# Generated by Django 3.2.25 on 2025-05-19 11:08

import core.models.project
import core.models.user
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20250517_1223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drawing',
            options={'ordering': ['project', 'phase', '-version']},
        ),
        migrations.AlterModelOptions(
            name='phase',
            options={'ordering': ['project', 'order']},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ['-start_date'], 'verbose_name_plural': 'Projects'},
        ),
        migrations.RemoveConstraint(
            model_name='usersubscription',
            name='unique_user_subscription',
        ),
        migrations.RemoveField(
            model_name='drawing',
            name='consultant',
        ),
        migrations.RemoveField(
            model_name='landdetail',
            name='attachemnts',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='current_phase',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='service_provider',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='stage',
        ),
        migrations.AddField(
            model_name='document',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phase_documents', to='core.phase'),
        ),
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='drawing',
            name='phase',
            field=models.ForeignKey(blank=True, help_text='Phase this drawing belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drawings', to='core.phase'),
        ),
        migrations.AddField(
            model_name='drawing',
            name='title',
            field=models.CharField(default='Untitled Drawing', max_length=255),
        ),
        migrations.AddField(
            model_name='drawing',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_drawings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='landdetail',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to=core.models.project.land_attachment_upload_path),
        ),
        migrations.AddField(
            model_name='phase',
            name='actual_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phase',
            name='expected_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phase',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Execution order of the phase'),
        ),
        migrations.AddField(
            model_name='phase',
            name='service_provider',
            field=models.ForeignKey(blank=True, help_text='Service Provider assigned to this phase', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_phases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='phase',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='active_phase',
            field=models.ForeignKey(blank=True, help_text='The currently active phase of the project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.phase'),
        ),
        migrations.AddField(
            model_name='projects',
            name='actual_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='expected_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='land_detail',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='core.landdetail'),
        ),
        migrations.AddField(
            model_name='projects',
            name='primary_service_provider',
            field=models.ForeignKey(blank=True, help_text='Main Service Provider if project is simple', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_service_provider', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotation',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='phase',
            field=models.ForeignKey(blank=True, help_text='Quotation for specific phase', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='core.phase'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='type',
            field=models.CharField(default='Initial Quotation', help_text='e.g Initial Design, Construction Bid', max_length=100),
        ),
        migrations.AddField(
            model_name='revision',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='status_reason',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='attachments',
            field=models.FileField(blank=True, upload_to=core.models.user.customer_attachement_upload_path),
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=core.models.project.general_document_upload_path),
        ),
        migrations.AlterField(
            model_name='document',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_documents', to='core.projects'),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_project_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='file',
            field=models.FileField(upload_to=core.models.project.drawing_upload_path),
        ),
        migrations.AlterField(
            model_name='phase',
            name='title',
            field=models.CharField(help_text='e.g Design, Foundation, Electrical Work', max_length=255),
        ),
        migrations.AlterField(
            model_name='projects',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='projects',
            name='title',
            field=models.CharField(default='Untitled Project', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quotation',
            name='service_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_quotations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Consultant', 'Consultant'), ('Interior Designer', 'Interior Designer'), ('Construction', 'Construction'), ('Maintenance', 'Maintenance'), ('Smart_Home', 'Smart_Home'), ('Admin', 'Admin')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userotp',
            name='otp_type',
            field=models.CharField(choices=[('signup', 'Signup'), ('reset_password', 'Reset Password'), ('phone_verification', 'Phone Verification')], default='signup', max_length=20),
        ),
        migrations.AlterField(
            model_name='userotp',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='phase',
            unique_together={('project', 'order')},
        ),
        migrations.RemoveField(
            model_name='phase',
            name='documents',
        ),
    ]
