# Generated by Django 3.2.25 on 2025-05-19 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20250519_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='end_date',
        ),
        migrations.AlterField(
            model_name='projects',
            name='primary_service_provider',
            field=models.ForeignKey(blank=True, help_text='Main Service Provider if project is simple', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
