# Generated by Django 3.2.25 on 2025-05-20 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20250520_1446'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MaintainanceProfile',
            new_name='MaintenanceProfile',
        ),
    ]
