# Generated by Django 3.2.25 on 2025-05-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_rename_maintainanceprofile_maintenanceprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='budget',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
